rest_api:
  https:
    certificate: /usr/local/share/ssl/amid/server.crt
    private_key: /usr/local/share/ssl/amid/server.key

ami:
  host: ari
  username: wazo_amid
  password: opensesame

ajam:
  host: ari
  verify_certificate: /usr/local/share/ssl/ari/server.crt
  username: wazo_amid
  password: opensesame

auth:
  host: auth
  verify_certificate: /usr/local/share/ssl/auth/server.crt

publish_ami_events: True

bus:
  host: rabbitmq
  username: guest
  password: guest
  startup_connection_delay: 1

uuid: 08c56466-8f29-45c7-9856-92bf1ba89b92
